var GAME_LEVELS = [
 
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                          o                                                                                   ",
   "                                                                                                              ",
   "                   xxx                                                                                        ",
   "       !  o  !                                                                                                ",
   "       !     !                                                            x                                   ",
   "       !  o  !            x                                               x                                   ",
   "       !     !                                                            x                                   ",
   "       !  o  !            o                                     xxxx   oo x                                   ",
   "                                                                          x                                   ",
   "          o              xxx                              xx          xxxxx                                   ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     xx     xx                     ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 xx                xx                 ",
   "                                                                                                              ",
   "                                                                                                         x    ",
   " xxxxxxxxxxxx      ^^^                                                                                   x    ",
   " x          x o xxxxxxxxx o xxxxxxxxx o xx                                                xx             x    ",
   " x          x   x       x   x       x   x                                     xx    xx                   x    ",
   " x @        xxxxx   o   xxxxx   o   xxxxx                                                    ^^      o ^^x    ",
   " xxxxxxxx                                     xxxxx       xx     xx     xxx                xxxxxxxxxxxxxxx    ",
   "!!!!!!!!x                                     x!!!x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!xxxxxxxxxx xxx xxxxxxxxxxxxxxxxxxxxxxxx!!!x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",],
  ["                                      x!!x                                                                   x!x  ",
   "                                      x!!x                                                                   x!x  ",
   "                                      x!!xxxxxxxxxx                                                          x!x  ",
   "                                      xx!!!!!!!!!!xx                                                         x!x  ",
   "                                       xxxxxxxxxx!!x                                              o   o   o &x!x  ",
   "                                                xx!x               o   o                                    xx!x  ",
   "                                                 x!x                                          xxxxx   x  xxxx!!x  ",
   "                                                 xvx         x     x   x                      x!!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            x                        ",
   "                                                               xxxx!!!!!xxxx            x                         ",
   "                                                                  xxxxxxx        xxx         xxx                  ",
   "                                                                                 x x         x x                  ",
   "                                                                                   x         x                    ",
   "                                                                                   xxx       x                    ",
   "                                                                                   x       ^^x                    ",
   "                                    ^^^                     o  o     x   x         x       xxx                    ",
   "               xx   xx        xxx   xxx                              x   x         x         x                    ",
   "              xx     xx         x   x                     xxxxxx     x   x   xxxxxxxxx       x                    ",
   "          x   x       xx        x o x                              x x   x   x             xxx                    ",
   "     @  x     x        x        x   x                   x        o   x   x   x               x                    ",
   "    xxx       x        x        x   x                        x   x   x   xxxxx   xxxxxx      x                    ",
   "    x x       x        x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!!!  x     =     x x         x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!!!!  xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x    o                 xx!!!!!!xx !!!!!!!!!!!!!!!!!!  xx     xx                     ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x                     xx!!!!!!xx  !                    x^^xxxxx                      ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                     xx                             ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !    !!!                                           "],
  ["                                                                                                              ",
   "                             xxxxxxxxxxxxxx     o o  x!!!!!!!!!!!!!!x                    vx                   ",
   "                             xxxxxxxxxxxxxx          x!!!!!!!!!!!!!!x                                         ",
   "                             x            x    xxxxxxxxxxxxxxxxxxxxxxx                o                       ",
   "                             xx     o     xx                                         xxx                      ",
   "  xxx                        xx     x     x                                         x!!!x                xxx  ",
   "  x x                        xx    xxx    x                                          xxx                 x x  ",
   "  x                          xx    xxx    xxxxxxx                        xxxxxx                            x  ",
   "  x                          xx           x                              x   x                             x  ",
   "  x                          xxx          x                              x x x                             x  ",
   "  x                                       x        |xxxx|    |xxxx|     xxx xxx    ^^^                     x  ",
   "  x                                o o    x                              x         xxx                     x  ",
   "  x                           xx                                        xxx       x!!!x                   x  ",
   "  x              xxx          xx   xxx                                             xxx                     x  ",
   "  x             x        x    xxxxxxxxxxxxxx  x oo x!!!!x oo x!!!!x oo xxxxx                               x  ",
   "  x      @     x o       ^^^^ x!!!!!!!!!!!x!!!x    x!!!!x    x!!!!x   xx!!!!!xx              ^^^^        o x  ",
   "  xxxxxxxxxxxxxxxxxxx!!!!xxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "          x   x  xxxx  x   x  x   x  x xxxx      x      x   xxxx   x    x    x                                ",
   "           x x   x  x  x   x  x   x    xxxx      x      x   x  x   x x  x    x                                ",
   "            x    x  x  x   x   x x     x          x  x  x   x  x   x  x x                                     ", 
   "            x    xxxx  xxxxx    x      xxxx        x  x     xxxx   x    x    x                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "   @                                                                                                          ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]                                                                                                                                   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
